name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build the app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run eslint
        run: npm run lint
      - name: Build
        run: npm run build

  build-and-push-to-dockerhub:
    name: Build the image and push to dockerhub
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sayamalvi/pizza-app-admin-dashboard
      IMAGE_TAG: build-${{ github.run_number }}

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f docker/prod/Dockerfile .
      - name: Push docker image to dockerhub
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
